name: Push to Container Registry 🛒

on:
  push:
    tags: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Release to Container Registry
    
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push the image
        run: |
          cd app/

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:${{github.ref_name}} .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:latest .
          
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic
