name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deploy to Staging

    environment: staging
    
    steps:
      - name: Running deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          port: ${{ secrets.SSH_PORT_STAGING }}
          script: |
            if [ -d ${{ vars.APP_STG_PATH }} ]; then
              echo "Changing directory to ${{ vars.APP_STG_PATH }}"
              cd ${{ vars.APP_STG_PATH }}

              echo "Stopping the running containers"
              docker compose -f docker-compose.yaml down pacmusic-stg-1 pacmusic-stg-2
              
              echo "Pulling the latest changes from the repository"
              git pull origin main
            else
              ssh-keyscan github.com >> ~/.ssh/known_hosts

              echo "Clone the repository to ${{ vars.APP_STG_PATH }}"
              git clone ${{ secrets.GIT_URL }} ${{ vars.APP_STG_PATH }}

              echo "Changing directory to ${{ vars.APP_STG_PATH }}"
              cd ${{ vars.APP_STG_PATH }}
            fi

            echo APP_STG_PORT="${{ secrets.APP_STG_PORT }}" > .env
            echo MINIO_STG_ENDPOINT="${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo MINIO_STG_ACCESS_KEY="${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo MINIO_STG_SECRET_KEY="${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            docker compose -f docker-compose.yaml up --build --detach pacmusic-stg-1 pacmusic-stg-2
  
      - name: Running simple testing
        run: |
          sleep 10
          curl ${{ secrets.STG_URL }}
